### ISSUE TITLE
I need to update the artboard

### ISSUE THREAD

**Issue by pluwen** [asivura/sketch-artboard-titles#1]
When I change the artboard name or position.
I need to update the Export Artboard, not to recreate one.

**Comment by asivura** [comment]
Hi @pluwen. I didn't understand what exactly you meant. Please, explain it in other words. Thanks.

**Comment by pluwen** [comment]
- Select all my artboards
- Run the plugin, I see an new artboard named "Export Artboard"
- Add a new artboard
- Select all my artboards, run plugin again
- I see an new artboard named "Export Artboard" again
- Now, I have 2 artboards named "Export Artboard"

I just need one artboards named "Export Artboard", though I can delete the first "Export Artboard", then run the plugin, but it is too much trouble.
Maybe this plugin can update the content in the "Export Artboard".

**Comment by asivura** [comment]
I suggest you just remove previous artboard with title before to add new one. Or create Pull Request for this.
